ERROR:root:Exception during registration: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(128)

[SQL: INSERT INTO "user" (first_name, last_name, email, password_hash) VALUES (%(first_name)s, %(last_name)s, %(email)s, %(password_hash)s) RETURNING "user".id]
[parameters: {'first_name': 'shannel', 'last_name': 'kirui', 'email': 'shannel@gmail.com', 'password_hash': 'scrypt:32768:8:1$LsAtxHMNubtvtWKB$fdb46e93e5ca48dc59f5a5ef092ac25aff1e42b42d3678b67d072b3a5f3fe29fa5234efacf16f6c7c4bc4afa80fb2ca40e893267ac561f537886aa498f4a7206'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
Traceback (most recent call last):
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(128)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/app/auth/routes.py", line 21, in register
    db.session.commit()
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4480, in _flush
    with util.safe_reraise():
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1419, in execute
    return meth(
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 526, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1641, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/shannel/Desktop/desktop projects/COM-TECH(3)/shannel/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(128)

[SQL: INSERT INTO "user" (first_name, last_name, email, password_hash) VALUES (%(first_name)s, %(last_name)s, %(email)s, %(password_hash)s) RETURNING "user".id]
[parameters: {'first_name': 'shannel', 'last_name': 'kirui', 'email': 'shannel@gmail.com', 'password_hash': 'scrypt:32768:8:1$LsAtxHMNubtvtWKB$fdb46e93e5ca48dc59f5a5ef092ac25aff1e42b42d3678b67d072b3a5f3fe29fa5234efacf16f6c7c4bc4afa80fb2ca40e893267ac561f537886aa498f4a7206'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
INFO:werkzeug:127.0.0.1 - - [06/Oct/2025 11:43:23] "POST /auth/register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2025 11:43:23] "[33mGET /static/style.css HTTP/1.1[0m" 404 -
INFO:werkzeug: * Detected change in '/home/shannel/Desktop/desktop projects/COM-TECH(3)/app/models/user.py', reloading
